# Generated by Django 3.1.1 on 2020-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='course_category',
            field=models.CharField(choices=[('AC', 'Art & Craft'), ('FR', 'Food Recipes'), ('L', 'Language')], max_length=10, null=True),
        ),
    ]
